// components/schedule/Day.vue
<template>
  <div
    :class="[
      'border-2 border-gray-200 rounded-lg w-full grow shrink-0',
      'py-1 flex gap-2',
      {
        ['border-l-4 border-main-200 border-l-main-400 shadow-lg shadow-main-100']:
          isToday,
      },
    ]"
  >
    <div class="relative h-full w-full">
      <ScheduleDayDivider
        v-for="i in timeSettings.stepsNumber - 1"
        :index="i * timeSettings.dividerStep"
        :timeInterval="[timeSettings.startHour, timeSettings.endHour]"
      />
      <ScheduleItem
        v-for="item in items"
        :key="`${item.title}${JSON.stringify(item.timeRange)}`"
        :item
        :timeInterval="[timeSettings.startHour, timeSettings.endHour]"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useCalendarSettings } from "~/composables/useCalendarSettings";
import type { PlainScheduleDayItem } from "~/types";

const props = defineProps<{
  index?: number;
  items?: PlainScheduleDayItem[];
}>();
const timeSettings = useCalendarSettings();

const today = new Date();
const isToday = props.index === (today.getDay() || 7);
</script>

// src/components/schedule/day.tsx
import {PlainScheduleDayItem} from "@/types";
import {calendarSettings} from "@/data";
import {DayDivider} from "@/components/schedule/dayDivider";
import {cn} from "@/utils/cn";
import {DayItem} from "@/components/schedule/dayItem";

interface DayProps {
    index?: number;
    items?: PlainScheduleDayItem[];
}

export const Day = (props: DayProps) => {
    const today = new Date();
    const isToday = props.index === (today.getDay() || 7);

    const dividersRange = Array(calendarSettings.stepsNumber - 1).fill(0).map((_, index) => index);

    return (
        <div
            className={cn(
                'border-2 border-gray-200 rounded-lg w-full grow shrink-0',
                'py-1 flex gap-2',
                isToday && 'border-l-4 border-main-200 border-l-main-400 shadow-lg shadow-main-100'
            )}
        >
            <div className="relative h-full w-full">
                {dividersRange.map(index => (
                    <DayDivider
                        key={index}
                        index={(index + 1) * calendarSettings.dividerStep}
                    />
                ))}
                {props.items?.map(item => (
                    <DayItem
                        key={`${item.title}${JSON.stringify(item.timeRange)}`}
                        item={item}
                    />
                ))}
            </div>
        </div>
    );
};
