// src/components/schedule/week.tsx
import {TimeRow} from "@/components/schedule/timeRow";
import {Day} from "@/components/schedule/day";
import {PlainScheduleDayItem, ScheduleDayItem} from "@/types";
import {useEffect, useState} from "react";
import {toPlainItem} from "@/utils";

interface WeekProps {
    items: ScheduleDayItem[];
}

export const Week = (props: WeekProps) => {
    const [processedItems, setProcessedItems] = useState<Record<number, PlainScheduleDayItem[]>>({});

    useEffect(() => {
        const itemsWithDays = props.items.map(toPlainItem);

        const itemsObject = itemsWithDays.reduce(
            (acc, item) => {
                if (item.day) {
                    acc[item.day] = acc[item.day] ?? [];
                    acc[item.day].push(item);
                }
                return acc;
            },
            {} as Record<number, PlainScheduleDayItem[]>,
        );

        setProcessedItems(itemsObject);
    }, [props.items]);

    return <>
        <TimeRow />
        <div className="grid grid-rows-7 gap-4 grow mb-4">
            {Array(7).fill(0).map((_, i) => (
                <Day
                    key={i}
                    index={i}
                    items={processedItems[i]}
                />
            ))}
        </div>
    </>
}

// components/schedule/Week.vue
<script setup lang="ts">
import type {ScheduleDayItem} from "~/types";
import {toPlainItem} from "~/utils";

const props = defineProps<{
  items: ScheduleDayItem[]
}>();

const processedItems = computed(() => {
  const itemsWithDays = props.items.map<ScheduleDayItem>((item) => ({
    ...item,
    day: item.startDate.getDay(),
  }));

  return itemsWithDays.reduce((acc, item) => {
    if (item.day) {
      acc[item.day] = acc[item.day] ?? [];
      acc[item.day].push(item);
    }
    return acc;
  }, {} as Record<number, ScheduleDayItem[]>);
});
</script>

<template>
  <ScheduleTimeline />
  <div class="grid grid-rows-7 gap-4 grow mb-4">
    <ScheduleDay v-for="i in 7" :index="i" :items="processedItems[i]?.map(toPlainItem)" />
  </div>
</template>
