// components/schedule/addModal/TimeRangeBlock.vue
<script setup lang="ts">
import TimeRangeSingleInput from "~/components/schedule/addModal/TimeRangeSingleInput.vue";
import type { FormState } from "@tanstack/vue-form";
import type { PlainScheduleDayItem } from "~/types";

defineProps<{
  field: any;
  subscriptionData: FormState<PlainScheduleDayItem>;
}>();
</script>

<template>
  <div class="flex gap-x-2 items-center w-full">
    <TimeRangeSingleInput label="Start" :field :subscriptionData :index="0" />
    <div class="hidden sm:block">&dash;</div>
    <TimeRangeSingleInput label="End" :field :subscriptionData :index="1" />
  </div>
</template>

// src/components/schedule/modal/timeRangeBlock.tsx
import {TimeRangeInput} from "@/components/schedule/modal/timeRangeInput";
import {FormState} from "@tanstack/form-core";
import {PlainScheduleDayItem} from "@/types";

interface TimeRangeBlockProps {
  field: any;
  subscriptionData: FormState<PlainScheduleDayItem>;
}

export const TimeRangeBlock = (props: TimeRangeBlockProps) => {
    return (
      <div className="flex gap-x-2 items-center w-full">
        <TimeRangeInput index={0} label="Start" {...props} />
        <div className="hidden sm:block"> - </div>
        <TimeRangeInput index={1} label="End" {...props} />
      </div>
    )
}
